<<<<<<< HEAD
---
title: "TransmissionLossExp"
author: "Becca Van Hoeck"
date: "12/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages and data

```{r}

library(dplyr)
library(tidyr)
library(ggplot2)

```

#### Summarizing data with dplyr to get error bars

```{r}

# TL for each signal was calculated manually

signalTL = read.csv("data/sound_exp/signalSPLdata.csv")

TL = signalTL[,c(1:10,21:30)]
TL = pivot_longer(TL,cols = c(11:20), names_to = "replicate", values_to = "TransLoss")

TLsummary = TL %>%
  group_by(site, distance, frequency, depthSt_cm) %>%
  summarise(meanTL = mean(TransLoss), quant5 = quantile(TransLoss, 0.05), quant95 = quantile(TransLoss, 0.95), 
            sdTL = sd(TransLoss))

ggplot(aes(x = distance, y = meanTL, color = site), data = TLsummary)+ theme_bw()+ 
  geom_point(aes(group = site), position = position_dodge(width = 0.5))+
  geom_errorbar(aes(x = distance, ymin = quant5, ymax = quant95), 
                width = 0.5, position = position_dodge(width = 0.5))+
  geom_line(aes(group = site), position = position_dodge(width = 0.5))+
  scale_color_manual(values = c("#39568CFF" ,"#55C667FF"))+
  facet_wrap(facets = TLsummary$frequency)+
  labs(x = "Disance", y = "Transmission Loss", legend = "Habitat")

min(signalTL$depthSt_cm)
max(signalTL$depthSt_cm)




```


